"""
Signal 2 — LLM-based classification (Groq)
==========================================
Asks a Groq-hosted LLM to judge whether text reads as human- or AI-written,
capturing semantic/stylistic coherence that the stylometric heuristics in
Signal 1 can't see.

Returns a tuple: (score, reason)
    score  : float in [0, 1]  (0 = human, 1 = AI)
    reason : short human-readable explanation from the model

Design notes:
- The model is asked to return STRICT JSON so we can parse a numeric score and
  a reason reliably (Groq's JSON mode requires the word "json" in the prompt).
- Any failure (missing key, network/API error, bad JSON) degrades gracefully to
  a neutral (0.5, <reason>) so the pipeline never crashes on Signal 2.

Dependencies: groq, python-dotenv (key loaded by the app via load_dotenv()).
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()  # ensure .env is loaded whether run standalone or imported

# Groq model to use. Override with GROQ_MODEL in .env if desired.
MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

# Neutral fallback when the signal can't produce a real judgment.
NEUTRAL_SCORE = 0.5

SYSTEM_PROMPT = (
    "You are a forensic text analyst. Judge whether the user's text was written "
    "by a human or generated by an AI language model. Consider semantic and "
    "stylistic coherence: overly uniform tone, generic phrasing, suspiciously "
    "balanced structure, and lack of genuine personal voice lean AI; idiosyncratic "
    "voice, uneven rhythm, and specific lived detail lean human.\n\n"
    "Respond with a JSON object and nothing else, in exactly this shape:\n"
    '{"ai_probability": <number between 0 and 1>, "reason": "<one concise sentence>"}\n'
    "0 means definitely human, 1 means definitely AI-generated. Be calibrated: "
    "use middle values when genuinely uncertain rather than guessing."
)

# Lazily-created client so importing this module never fails on a missing key.
_client = None


def _get_client():
    """Create (once) and return a Groq client, or None if no API key is set."""
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            return None
        _client = Groq(api_key=api_key)
    return _client


def _clamp(value):
    """Coerce to float in [0, 1]; return NEUTRAL_SCORE if not a valid number."""
    try:
        return max(0.0, min(1.0, float(value)))
    except (TypeError, ValueError):
        return NEUTRAL_SCORE


def run_signal_2(text):
    """
    Classify `text` with the Groq LLM.

    Returns (score, reason). Falls back to (0.5, <explanation>) on any error.
    """
    if not text or not text.strip():
        return NEUTRAL_SCORE, "Signal 2 skipped: empty text."

    client = _get_client()
    if client is None:
        return NEUTRAL_SCORE, "Signal 2 unavailable: GROQ_API_KEY not set."

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            response_format={"type": "json_object"},  # force valid JSON back
            temperature=0,                             # deterministic judgment
            max_tokens=200,
        )
        content = response.choices[0].message.content
        data = json.loads(content)
        score = _clamp(data.get("ai_probability"))
        reason = str(data.get("reason", "")).strip() or "No reason provided."
        return score, reason
    except Exception as exc:  # network, auth, JSON, or API errors
        return NEUTRAL_SCORE, f"Signal 2 error: {exc}"


if __name__ == "__main__":
    sample = (
        "Furthermore, it is important to note that the utilization of renewable "
        "energy sources provides numerous benefits. Additionally, these benefits "
        "include reduced emissions, improved sustainability, and long-term cost savings."
    )
    s, r = run_signal_2(sample)
    print(f"Signal 2 score: {s:.3f}  |  reason: {r}")
